---
title: David Demaree
timezone: America/New_York
collections:
  posts:
    title: Posts
    output: true
  publications:
    title: Publications
    output: false
  talks:
    title: Talks
    output: false
  uploads:
    title: Uploads
    output: true
destination: _site
email: david@demaree.me
description: David Demaree's web site
baseurl: 
url: https://demaree.me
domain: demaree.me
twitter_username: ddemaree
github_username: ddemaree
markdown: kramdown
exclude:
- Gemfile
- Gemfile.lock
- netlify.toml
- package.json
- package-lock.json
- webpack.config.js
- node_modules
defaults:
- scope:
    path: ''
  values:
    show_header: true
- scope:
    path: ''
    type: posts
  values:
    layout: default
    permalink: "/posts/:year/:title/"
- scope:
    path: ''
    type: pages
  values:
    layout: default
- scope:
    path: ''
    type: talks
  values:
    layout: default
