baseURL = "http://demaree.me/"
languageCode = "en-us"
title = "David Demaree"

[params]
cloudinaryBase = "res.cloudinary.com/demaree/image"

[permalinks]
posts = "/p/:title"
blog = "/p/:slug"

[markup.goldmark.renderer]
unsafe = true