baseURL = "http://demaree.me/"
languageCode = "en-us"
title = "David Demaree"

# Disable Hugo's built-in Alias feature, to utilize Netlify Redirects instead:
disableAliases = true

# sectionPagesMenu = "main"

[params]
cloudinaryBase = "res.cloudinary.com/demaree/image"

[permalinks]
posts = "/p/:title"
blog = "/p/:slug"

[markup.goldmark.renderer]
unsafe = true

[menu]
[[menu.social]]
  identifier = "twitter"
  name = "Twitter"
  pre = "<i class='fab fa-twitter'></i>"
  url = "https://twitter.com/ddemaree"
  weight = -100

[[menu.social]]
  identifier = "instagram"
  name = "Instagram"
  pre = "<i class='fab fa-instagram'></i>"
  url = "https://instagram.com/ddemaree"

[[menu.social]]
  identifier = "linkedin"
  name = "LinkedIn"
  pre = "<i class='fab fa-linkedin'></i>"
  url = "https://linkedin.com/in/ddemaree"


# Custom Output formats are outlined here: https://gohugo.io/templates/output-formats. See also: https://gohugo.io/news/http2-server-push-in-hugo/

# Create the media type https://gohugo.io/templates/output-formats#media-types
[mediaTypes]
[mediaTypes."text/netlify"]
delimiter = ""
suffixes = [""]

# configure output formats: https://gohugo.io/templates/output-formats#configure-output-formats
# [outputFormats]
# [outputFormats.HEADERS]
# baseName = "_headers"
# isPlainText = true
# mediatype = "text/netlify"
# notAlternative = true

[outputFormats.REDIR]
baseName = "_redirects"
isPlainText = true
mediatype = "text/netlify"
notAlternative = true

# For the home page, output the formats we created: https://gohugo.io/templates/output-formats#customizing-output-formats
[outputs]
home = [
"HTML",
"REDIR"
]