version: '3.3'

volumes:
  db_data:
  node_modules:

services:
  app:
    environment:
    - NODE_ENV=development
    expose:
    - 3000
    ports:
    - "3000:3000"
    build: .
    volumes: 
      - ${ROOT_PATH:-.}:/app:rw
      # The volume is effectively hiding node_modules from the host and must be in this order
      - node_modules:/app/node_modules