[Settings]
  ID = "demaree-next"

[build]
  command = "gatsby build"
  publish = "public"

[context.gatsby-2019-fml]
  command = "gatsby build"
  publish = "public"

[context.eleventy-2020]
  command = "npm run build"
  publish = "_site"

[context.eleventy-compare]
  command = "npm run build"
  publish = "public

[[plugins]]
  package = "netlify-plugin-gatsby-cache"