[Settings]
  ID = "demaree-next"

[build]
  command = "yarn run build"
  publish = "dist"

[build.environment]
  NODE_ENV = "production"
  HUGO_ENV = "production"
  NODE_VERSION = "15"
  HUGO_VERSION = "0.82.0"
  HUGO_ENABLEGITINFO = "true"

[context.deploy-preview]
  command = "yarn run build:preview"

[context.branch-deploy]
  command = "yarn run build:preview"

[dev]
  command = "yarn start"
  targetPort = 3000
  framework = "#custom"