[Settings]
  ID = "demaree-next"

[build]
  command = "yarn build"
  publish = "public"

[build.environment]
  NODE_ENV = "production"
  HUGO_ENV = "production"
  NODE_VERSION = "12"
  HUGO_VERSION = "0.80.0"
  HUGO_ENABLEGITINFO = "true"

[context.deploy-preview]
  command = "yarn build"

[context.branch-deploy]
  command = "yarn build"