[Settings]
  ID = "demaree-next"

[build]
  command = "npm run build"
  publish = "_site"

[build.environment]
  NODE_ENV = "production"
  HUGO_ENV = "production"
  ELEVENTY_ENV = "production"
  ELEVENTY_PRODUCTION = "true"
  NODE_VERSION = "12"
  HUGO_VERSION = "0.80.0"
  HUGO_ENABLEGITINFO = "true"

[context.deploy-preview]
  command = "npm run build"

[context.branch-deploy]
  command = "npm run build"