[Settings]
  ID = "demaree-next"

[build]
  command = "hugo --gc --minify"
  publish = "public"

[build.environment]
  NODE_ENV = "production"
  NODE_VERSION = "12"
  HUGO_VERSION = "0.80.0"
  HUGO_ENABLEGITINFO = "true"

[context.deploy-preview]
  command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
  command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

[context.eleventy-2007]
  command = "npm run build"
  publish = "_site"