[Settings]
  ID = "demaree-next"

[build]
  command = "npm run build"
  publish = "public"
  environment = { NODE_ENV = "production", NODE_VERSION = "12" }

[context.eleventy-2020]
  command = "npm run build"
  publish = "_site"

[[plugins]]
  package = "netlify-plugin-gatsby-cache"